[tool.poetry]
name = "pyjwt-key-fetcher"
version = "0.1.0"
description = "Async library to fetch JWKs for JWT tokens"
authors = ["Digital Living International Ltd"]
license = "BSD-3-Clause"
readme = "README.md"
repository = "https://github.com/digitalliving/pyjwt-key-fetcher"
packages = [
    {include="pyjwt_key_fetcher", from="."}
]

[tool.poetry.dependencies]
python = "^3.8"
PyJWT = {extras = ["crypto"], version = "^2.1.0"}
aiohttp = {extras = ["speedups"], version = "^3.7.4"}
cachetools = "^4.2.2"
aiocache = "^0.11.1"

[tool.poetry.dev-dependencies]
invoke = "^1.5.0"
mypy = "^0.812"
pytest = "^6.2.4"
pytest-asyncio = "^0.15.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
